version: '3.8'

services:
  api_admin:
    build: ./API/ServerAdmin
    ports:
      - "4001:4001"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=CFNdb;Username=CFNadmin;Password=ZiuRCR2e3NN2LMgZSLR4

  api_user:
    build: ./API/ServerUser
    ports:
      - "4000:4000"
    networks:
      - backend
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Host=localhost;Port=5432;Database=CFN;Username=postgres;Password=9669

  client:
    build: ./Client/User
    ports:
      - "3000:3000"
    networks:
      - frontend

  admin:
    build: ./Client/Admin
    ports:
      - "3001:3001"
    networks:
      - frontend

  # db:
  #   image: postgres:latest
  #   restart: always
  #   environment:
  #     POSTGRES_DB: CFNdb
  #     POSTGRES_USER: CFNadmin
  #     POSTGRES_PASSWORD: ZiuRCR2e3NN2LMgZSLR4
  #   networks:
  #     - backend
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

networks:
  frontend:
  backend:


volumes:
  pgdata:
